/**
 * Equivalence tests: the JS engine must reproduce the Python one exactly.
 *
 * `__fixtures__/golden.json` was generated by backend/scripts/dump_golden.py
 * from app/services/engine.py. It is the oracle for this port, and it has to
 * be: Chess.com's own accuracy comes from CAPS2, a different model, so it can
 * say a number looks believable but never that `move_accuracy` was transcribed
 * correctly.
 *
 * The two game cases are the strong ones. Every engine call the Python made was
 * taped in order, so replaying the tape forces this code to pick the same
 * deep-pass targets and pair the same positions to land on the same result -
 * with no Stockfish running and nothing nondeterministic.
 *
 * A failure here is never "the test is flaky". It is a behaviour change, and it
 * needs saying out loud before the fixture is regenerated.
 */

import { describe, expect, it } from "vitest";

import golden from "../__fixtures__/golden.json";
import { analysePgn, deepTargets } from "../analyze.js";
import * as scoring from "../scoring.js";

// Python's math.exp and V8's Math.exp are both correctly rounded in practice
// but are not the same implementation, so raw transcendental output is compared
// with a tolerance. Everything that reaches the user has been through
// `round(x, 1)` first and is compared exactly.
const EPSILON = 1e-9;

function expectClose(actual, expected, label) {
  if (expected === null || expected === undefined) {
    expect(actual, label).toBe(expected);
    return;
  }
  expect(Math.abs(actual - expected), `${label}: got ${actual}, want ${expected}`).toBeLessThan(
    EPSILON,
  );
}

describe("constants", () => {
  it("match the Python module", () => {
    for (const [name, value] of Object.entries(golden.constants)) {
      expect(scoring[name], name).toBe(value);
    }
  });
});

describe("pure functions", () => {
  it("clip", () => {
    for (const { cp, out } of golden.pure.clip) expect(scoring.clip(cp), `cp=${cp}`).toBe(out);
  });

  it("win_percent_white", () => {
    for (const { cp, out } of golden.pure.win_percent_white) {
      expectClose(scoring.winPercentWhite(cp), out, `cp=${cp}`);
    }
  });

  it("move_accuracy", () => {
    for (const { before, after, out } of golden.pure.move_accuracy) {
      expectClose(scoring.moveAccuracy(before, after), out, `${before}->${after}`);
    }
  });

  it("judgment", () => {
    for (const { cp_loss, out } of golden.pure.judgment) {
      expect(scoring.judgmentFor(cp_loss), `cp_loss=${cp_loss}`).toBe(out);
    }
  });

  // The one that would silently rot the numbers: Python rounds ties to even and
  // rounds the exact binary value, so round(0.25, 1) is 0.2 where
  // Math.round(0.25 * 10) / 10 is 0.3.
  it("round to one decimal, Python semantics", () => {
    for (const { value, out } of golden.pure.round1) {
      expect(scoring.roundTo(value, 1), `round(${value}, 1)`).toBe(out);
    }
  });

  it("differs from the naive rounding somewhere, or this test proves nothing", () => {
    const naive = (v) => Math.round(v * 10) / 10;
    const divergent = golden.pure.round1.filter(({ value, out }) => naive(value) !== out);
    expect(divergent.length).toBeGreaterThan(0);
  });
});

describe("pipeline", () => {
  it("deep_targets", () => {
    for (const { positions, out } of golden.pipeline.deep_targets) {
      expect(deepTargets(positions), JSON.stringify(positions)).toEqual(out);
    }
  });

  it("volatility_weights", () => {
    for (const { win_percents, out } of golden.pipeline.volatility_weights) {
      const actual = scoring.volatilityWeights(win_percents);
      expect(actual.length, `n=${win_percents.length}`).toBe(out.length);
      out.forEach((expected, i) => {
        expectClose(actual[i], expected, `n=${win_percents.length} i=${i}`);
      });
    }
  });

  it("blend_accuracy", () => {
    for (const { pairs, out } of golden.pipeline.blend_accuracy) {
      expect(scoring.blendAccuracy(pairs), JSON.stringify(pairs).slice(0, 60)).toBe(out);
    }
  });

  it("aggregate", () => {
    for (const { moves, out } of golden.pipeline.aggregate) {
      expect(scoring.aggregate(moves), `${moves.length} moves`).toEqual(out);
    }
  });
});

describe("analysePgn against taped engine calls", () => {
  for (const [name, game] of Object.entries(golden.games)) {
    it(name, async () => {
      const tape = [...game.calls];
      const seen = [];

      const evaluate = async (fen, limit) => {
        const call = tape.shift();
        expect(call, `ran out of taped calls at #${seen.length}`).toBeDefined();
        seen.push(fen);
        // The FEN and the search limit are part of what is being verified: a
        // different position or a different depth would make the returned eval
        // an answer to a question this code never asked.
        expect(fen, `call #${seen.length - 1} position`).toBe(call.fen);
        expect(limit.depth, `call #${seen.length - 1} depth`).toBe(call.limit_depth);
        expect(limit.time ?? null, `call #${seen.length - 1} time`).toBe(call.limit_time ?? null);
        return call.result;
      };

      const result = await analysePgn(game.pgn, {
        evaluate,
        engineName: game.expected.engine_name,
        settings: game.settings,
      });

      expect(tape.length, "taped calls left unconsumed").toBe(0);
      expect(result).toEqual(game.expected);
    });
  }

  it("asks for every position once per pass", () => {
    for (const [name, game] of Object.entries(golden.games)) {
      const plies = game.expected.moves.length;
      expect(game.expected.scanned_positions, `${name} scan`).toBe(plies + 1);
      expect(game.calls.length, `${name} total`).toBe(
        game.expected.scanned_positions + game.expected.deep_positions,
      );
    }
  });
});
